### ISSUE TITLE
번역 오류

### ISSUE THREAD

**Issue by DublinCity** [ParkSB/javascript-style-guide#1]
7.1 Use named function expressions instead of function declarations. eslint: func-style jscs: disallowFunctionDeclarations

7.1 함수표현식 대신 함수선언을 사용하세요. eslint: func-style jscs: disallowFunctionDeclarations
=> 7.1 함수선언식 대신 이름있는 함수표현식을 사용하세요.

**Comment by ParkSB** [comment]
감사합니다!
